### PR TITLE
Hide cursor while searching + exit gracefully upon SIGINT

### PR DESCRIPTION
**Pull request by meowgorithm**
This PR:

* Hides the cursor while searching
* Exits gracefully when the user presses <kbd>ctrl-c</kbd>

Nice work on this, by the way!

### CODE REVIEW

**Comment by irevenko** [comment]
🤩 Dude thank you some much for submiting such PR, amazing job 👍
🥳 I appreciate your Work a lot!!

**Comment by irevenko** [comment]
🤯 It is actually amazing beacause you put in your time, such a legend no cap 👏

**Comment by meowgorithm** [comment]
My pleasure! I'm very happy to contribute to such a fun CLI! 🎊

**Comment by irevenko** [comment]
@meowgorithm _WAIT YOU CREATED **[BUBBLE TEA](https://github.com/charmbracelet/bubbletea)** OMG BIG FAN AND UR HELPING OUT HERE YOOOO INSANE, POWER OF OPEN SOURCE RIGHT HERE_ 💪

**Pull request merged**
